spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius-dev
        group: DEFAULT_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        username: ${spring.cloud.nacos.discovery.username}
        password: ${spring.cloud.nacos.discovery.password}
        namespace: sagittarius-dev
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - nacos:sagittarius-common?refreshEnabled=true
      - nacos:sagittarius-gateway?refreshEnabled=true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    # nacosdiscovery endpoint
    nacosdiscovery:
      enabled: true
    # health endpoint
    health:
      show-details: always
