server:
  port: 8801
spring:
  application:
    name: sagittarius-auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius
        group: sagittarius
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        username: nacos
        password: nacos
        namespace: sagittarius
        file-extension: yaml
        group: sagittarius
  config:
    import:
      - nacos:sagittarius-common?refreshEnabled=true
      - nacos:sagittarius-auth?refreshEnabled=true