server:
  port: 8804

spring:
  application:
    name: sagittarius-category
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius
        group: sagittarius
      config:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius
        file-extension: yaml
        group: sagittarius
  config:
    import:
      - nacos:sagittarius-category?refreshEnabled=true