server:
  port: 8809

spring:
  application:
    name: sagittarius-monitor
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius
        group: sagittarius
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        username: ${spring.cloud.nacos.discovery.username}
        password: ${spring.cloud.nacos.discovery.password}
        namespace: sagittarius
        file-extension: yaml
        group: sagittarius
  config:
    import:
      - nacos:sagittarius-common?refreshEnabled=true
      - nacos:sagittarius-monitor?refreshEnabled=true