server:
  port: 8802
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
        namespace: sagittarius-dev
        group: DEFAULT_GROUP
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        username: nacos
        password: nacos
        namespace: sagittarius-dev
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import:
      - nacos:sagittarius-common?refreshEnabled=true
      - nacos:sagittarius-user?refreshEnabled=true